### ISSUE TITLE
New Safety Feature Logic

### ISSUE THREAD

**Issue by v-s-c-o-p-e** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#10]
idea: 
only at the end of ebike_control_motor safety checks are done before setting 
ebike_app_set_target_adc_battery_max_current  and motor_set_pwm_duty_cycle_target 

safety function:

if would be best if we read cadence , torque , wheelspeed , throttle in safety check again (or have a extra safety_raw_value_... of each value if read again is too time consuming) to be save that no other piece of code changed these values before.

safety check:
```
read_all_values_again() // cadence, torque , wheelspeed ,throttle 

default mode = stop

if(!brake_is_set()) 
    if(!ui8_motor_assistance_startup_without_pedal_rotation){
        if(throttle==0)
            if (cadence > 0 && torque > 0 && wheelspeed > 0) -> mode = run
        else if (throttle > 0)
            if wheelspeed > 0 -> mode = run
    else 
        if(throttle > 0 || torque > 0 )
            if(wheelspeed == 0) mode = run // maybe we need to add a cadence thing also... have to check in real life


if(mode == run){
    !max_current_check -> set max current
    !max_speed_check -> max speed ??? maybe not needed
    ....
}

if(mode == run){
    start_engine()
else
    stop_engine
}
```

create a start_engine function which powers the motor with right current.
create a stop_engine function which resets all values in one place (boost_timer....)

what you think.
with that safety thing in place we can delete all the brake_is_set cadence checks ... in other parts of the code.
will make the firmware more safe and easier to maintain in think

**Comment by leon927** [comment]
@casainho - This is also implemented in the 0.19.0! Able to be closed :)
