### ISSUE TITLE
Wrong voltage in FW 0.20.0

### ISSUE THREAD

**Issue by d3rsch0rsch** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#131]
I saw that the voltage reads in the KT3 are about 1.5V off.
I verified with another user from german forum, same there. So either the voltage reads, or some offset is incorrect.

Example: Voltage read in KT3 - 60.1V
Voltage read on battery (multimeter) 58.8V (Charging cap with 14S)

**Comment by casainho** [comment]
Update to latest firmware version.
