### ISSUE TITLE
firmware v1.0.0 dwonload

### ISSUE THREAD

**Issue by josch591** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#137]
i'm searching for the anounced TSDZ2-v1.0.0.hex - the latest release (may, 26th) contains just the the ones up to .57.3 ?

**Comment by jpt000** [comment]
Hi! Had the same problem as you but then found it in the SW102 download page:
https://github.com/OpenSource-EBike-firmware/Color_LCD/releases
Cheers

**Comment by josch591** [comment]
Thanks a lot!
