### ISSUE TITLE
Walk assist mode

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#14]
Moved from TongSheng_TSDZ2_motor_controller_firmware repository: OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#7

**Comment by lightcore-x** [comment]
Some interesting ideas from @casainho https://github.com/OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware/issues/7#issuecomment-424902283

**Comment by leon927** [comment]
Walk Assist is now implemented in 0.18! :) I think this is completely solved.
