### ISSUE TITLE
TSDZ2-ESP-32 compatibility?

### ISSUE THREAD

**Issue by washichi** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#160]
I'm currently using this firmware for my TSDZ2, and would like to use the android app to change the configuration & monitor.
Does the emmebrusa firmware support the ESP32 bluetooth/wifi interface? Or are those projects existing next to each other?

I don't want to make the investment, to then find out it is not compatibly, and for sure someone here knows if it is compatible.

I'm talking about the TSDZ2-ESP32 project:
https://github.com/TSDZ2-ESP32/TSDZ2-ESP32-Wiki/

**Comment by casainho** [comment]
.You should got an invitation-
