### ISSUE TITLE
Implement button fast/multiple clicks

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#19]
To increase the amount of possibilities because we have only three buttons right now.

Can possibly be used for:

- Offroad mode
- Max power screen
- ODO
- Emergency button / Disable motor?
- Reset to factory defaults?

**Comment by casainho** [comment]
I started but after by mistake I lost the code. I was doing this:

Quick click + Long click. Quick click would be some less than 0.8 seconds. I was expanding the state machine of the buttons....

**Comment by casainho** [comment]
And I was expecting to use that fast+long clicks to change the info on odometer. Let's say we have a field only to show battery voltage and battery current, we would change between then with this new clicks.

Also, the same for like pedals: pedal power; pedal cadence.
Trip distances....

**Comment by lightcore-x** [comment]
Works great!
