### ISSUE TITLE
Change default amount of assist levels to 5

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#2]
Now the default is 9 which is too much to be very useful IMHO. Previously it was 5 levels only.

**Comment by casainho** [comment]
Maybe we should use a number that is the most common/popular number used over the other system, maybe take example for what the popular Bafang or Bosh motors use??

**Comment by lightcore-x** [comment]
Fully agree with you @casainho. I don't have a commercial ebike myself. Is anyone able to deliver this info?

**Comment by lightcore-x** [comment]
Implemented with #47
