### ISSUE TITLE
Protection for stalled bicycle wheel

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#21]

**Comment by lightcore-x** [comment]
I've created branch bug/21-24-eeprom-stall-protection to work on this issue and #24 
Please commit no unrelated changes, it's better to create a new branch then.

Please continue developing on bug/21-24-eeprom-stall-protection and we should review the pull request to master together before merging it.

**Comment by casainho** [comment]
Improved and now seems to work well for me: 264d97788757844c57db69e80e7467a0b35be943

**Comment by lightcore-x** [comment]
Merged to master, will be tested before releasing version 0.15.0

**Comment by lightcore-x** [comment]
It added a bit more complexity to the code but I think it works well.
