### ISSUE TITLE
EEPROM fail to write default values on LCD3

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#24]

**Comment by casainho** [comment]
Well, seems that this do no fix :-(

Seems that sometimes it works and others don't. Maybe we should add a delay after writing to eeprom and before shutoff the micro. We know there is a considerable delay to write to EEPROM... - I don't have more clues.

**Comment by lightcore-x** [comment]
I've created branch bug/21-24-eeprom-stall-protection to work on this issue and #21 
Please commit no unrelated changes, it's better to create a new branch then.

Please continue developing on bug/21-24-eeprom-stall-protection and we should review the pull request to master together before merging it. I'll also try to fix this ;)

**Comment by lightcore-x** [comment]
@casainho You said somewhere that some specific EEPROM values weren't reset? Is this consistent behavior? Please let me know which EEPROM values...

**Comment by lightcore-x** [comment]
Cannot be reproduced anymore by @casainho and myself
