### ISSUE TITLE
Add High Cadence option in Menu

### ISSUE THREAD

**Issue by jbalat** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#27]
Add special menu item to enable or disable high cadence
when setting this value to true.
MAX ERPS change from 560 to 700
MAX CADENCE change from 110 to 130
FOC ANGLE change from 80 to 115 (for 36v motor)  
have not tried 48v motor but maybe use the same ratio, don’t want those guys to miss out ;)

**Comment by lightcore-x** [comment]
@jbalat Thanks!

I've implemented this and I love it! I will release this feature soon.

See pull request #28 for more details about the implementation and configuration.

**Comment by lightcore-x** [comment]
Released in version 0.14.3!
