### ISSUE TITLE
High cadence mode for 48v motor

### ISSUE THREAD

**Issue by bbeschea** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#29]
I think it would be useful to have this experimental enhancement also for 48v.

**Comment by bbeschea** [comment]
I can try to make a similar implementation also for 48v motors. 
Is it possible to create a branch/pull request so we can have a conversation on the code?

**Comment by casainho** [comment]
Yes, please go ahead.

**Comment by leon927** [comment]
This issue is basically the same as the "field weakening" that is labeled as an enhancement. Maybe close this issue and keep the **Field weakening #11**.
