### ISSUE TITLE
Bike computer functionality

### ISSUE THREAD

**Issue by troebi2** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#44]
I wrote this issues already in the kt3 folder:

It may be very helpful, when the KT3 display may show the main functions of a trip computer.

ODO (settable in the config menu when changing the bike/motor/firmware)
 DST (e.g. resettable with a triple button press)
 MAX maximum speed (e.g. resettable with a triple button press)
 AVG average speed (e.g. resettable with a triple button press)

The KT3 display (also other displays)  has the icons.

**Comment by leon927** [comment]
This is solved in 0.18! :)
