### ISSUE TITLE
Assist level and start power boost now work as a factor of rider pedal human power

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#46]

**Comment by AndyME2** [comment]
from what firmware on? there is no new release so far, no?
I am just asking because you post it now, but the change must have occured sometime in the past?

**Comment by casainho** [comment]
On forum I posted the link to the sources and explained about a possible release.

**Comment by AndyME2** [comment]
Oh....on the other one...
pls. post the link of the developer forum, i lost it....

**Comment by lightcore-x** [comment]
Merged to master, will be tested before releasing version 0.15.0

**Comment by lightcore-x** [comment]
Tested, works great!
