### ISSUE TITLE
Buttons become unresponsive when pressed too long in config menu (0.15.0)

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#51]
While in the configuration menu (when changing a setting) do a long press on the up or down buttons. Afterward, it doesn't respond to these buttons anymore. One has to toggle the power to fix this.

**Comment by casainho** [comment]
I got that type of issue during development and that is because the event happens and needs to be cleared at the end of cycle other way that happens. It is like if once one event happens, no one more is detect while the previous is cleared.

**Comment by lightcore-x** [comment]
Thanks for your explanation. I'll see if I can locate the issue and fix it.

**Comment by leon927** [comment]
Should this be closed, @casainho?
