### ISSUE TITLE
CRC8 option for more efficiency

### ISSUE THREAD

**Issue by sbridger** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#55]
I notice you use CRC16 in the protocol. 
CRC8 is less popular,  but it is a fast (256byte) table lookup, and only requires one protocol byte. 
It retains the key advantages of CRC over checksum (zero run immunity etc)

So an option if you are looking for a bit of efficiency at the motor end, or an extra payload byte.

https://electronics.stackexchange.com/questions/33821/calculating-a-simple-crc

**Comment by casainho** [comment]
Thanks!! That is something I would like to do and you are right.

Do you wan to do it and make a pull request?

**Comment by sbridger** [comment]
If I do start working with the code, then I will.

a constant table is in realterm : crc8.pas

**Comment by casainho** [comment]
CRC16 seems a good bet now that configurations package has about 100 bytes.
