### ISSUE TITLE
Boost not working in 0.16

### ISSUE THREAD

**Issue by AndyME2** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#56]
Setting boost to "on" (menu 4) does not bring any boost effect,  but on the contrary it will make problems at restarts after stops at e.g. red lights, where the motor does not kick in for a couple of seconds in many cases.

Boost used to work in previous versions. Now it does not.

**Comment by leon927** [comment]
Is this solved?

**Comment by casainho** [comment]
I think it is not, at least none was done for that.

**Comment by leon927** [comment]
Should we close this then or remove release 0.16? What do you recommend Casainho?

**Comment by casainho** [comment]
Release 0.16 is deleted now. But I will also close this.
