### ISSUE TITLE
Prevent drag when pushing the bike backwards

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#6]
It seems that we're still powering the motor coils when cadence and speed is zero.

**Comment by troebi2** [comment]
It seems to be released, when you give a little torque (just lay your leg softly on the pedals) on the pedals.

**Comment by lightcore-x** [comment]
Thanks for the information! I'll try this myself as well.

**Comment by sbridger** [comment]
A related non-software issue: when touring, and the system dies, what is the easiest way to field remove the blue gear to eliminate the drag?

**Comment by casainho** [comment]
I think is really hard to do. I wishnthere was a way to have quick access because I need to have my metal gear well lubricated and it is hard to do it....

**Comment by casainho** [comment]
I found the reason for this issue!!

When we push the ebike backwards, the pedals rotate and also there the torque -- this is easy to very on LCD3 looking at pedal cadence and torque sensor values.
So, with cadence and torque sensor when we push the ebike backwards, motor will be powered as if we was doing force with our legs on the pedals.

The solution: I think we need to implement detection of pedals rotation and if the rotate backwards, we should set torque sensor value = 0 as also pedal cadence = 0.

**Comment by lightcore-x** [comment]
@casainho Very nice, I'm able to fix and test this in the upcoming days.

**Comment by casainho** [comment]
Grab the code from here, should be fast to have it done!!!

1. https://github.com/OpenSource-EBike-firmware/BMSBattery_S_controllers_firmware/blob/78bbbc4ca328e8bfe3d8414280a0583528237b3e/firmware/motor.c

2. https://github.com/OpenSource-EBike-firmware/BMSBattery_S_controllers_firmware/blob/78bbbc4ca328e8bfe3d8414280a0583528237b3e/firmware/ebike_app.c

**Comment by lightcore-x** [comment]
Will do, thanks! 😄

**Comment by lightcore-x** [comment]
@casainho Unfortunately this doesn't seem to work. I also don't see the torque increasing much when moving the bike backward. Sometimes the torque even decreases! There is hardly any change at all. I only see the motor speed (ERPS) increase very fast but I think this simply means that the motor magnets are moving? There is no change in drawn wattage too (on display).

**Comment by casainho** [comment]
W9rks for me if I put a very high gear, that will make more torque and speed of the chainring...

**Comment by lightcore-x** [comment]
Of course, I can imagine that it's possible to get some torque that way but all I am saying is that torque isn't the (only) issue if it's an issue at all...

**Comment by casainho** [comment]
I get torque and cadence, then I see that PWM increases!! All this I see on LCD3.

**Comment by lightcore-x** [comment]
Hmm maybe the difference is because of the few changes in this branch which I was using: 😉 
https://github.com/OpenSource-EBike-firmware/TSDZ2-Smart-EBike/tree/bug/6-prevent-drag

**Comment by Ranla1** [comment]
Hey, if the motor know that the pedals are turning backwards. Can you aktivet brakesensor?

**Comment by casainho** [comment]
Done on 0.19.0.
