### ISSUE TITLE
Correct calculated value of Watts/hour

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#7]
_I tested the power consumption with a watt-meter this morning, here are the numbers :_

_LCD3 power usage : 60.6Wh
Turnigy watt-meter : 87Wh_

_Peak : 624W_

_So there is a difference. Hope it helps for future developments._

**Comment by casainho** [comment]
Works well for SOC if: Simple full discharge your battery and take note on the counted Wh value on LCD3, then enter that value on LCD3 configuration and you will see that SOC works very well!!

I know that there is a time dependency on the calculation, as it is watts/hour. If the time is incorrect, then calcs will fail. And the time counting depends on the other code running for all the other tasks........

**Comment by casainho** [comment]
If the issue is the time dependency on the calculation, maybe we can make a timer interrupt as a fixed interval that will calculate the SOC. The only interrupt on current code is the UART receive data that should take very small time while the SOC is calculated every 100ms -- with the timer interrupt that fixed time of 100ms should be guaranteed.

**Comment by lightcore-x** [comment]
@casainho is this improved with https://github.com/OpenSource-EBike-firmware/TSDZ2-Smart-EBike/commit/7cf028c383e753942f4a732f728e4d213bf0dd08 ?

This issue can be closed?

**Comment by casainho** [comment]
Yes. I will close.
