### ISSUE TITLE
Use SDCC on Windows.

### ISSUE THREAD

**Issue by rmnlsn** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#73]
Hello everyones, 

ther's someone working on windows to compile the TSDZ2's firmware?

**Comment by leon927** [comment]
Hi! Yes, I do! Do you have more questions? I think it will be best to ask them in the official thread so that the entire community can help:

https://endless-sphere.com/forums/viewtopic.php?f=30&t=93818&start=9999

If it is a small question you are free to ask it here as well.

Good luck!

**Comment by rmnlsn** [comment]
I did as you told me. THX.
