### ISSUE TITLE
incorrect offset averaging ?

### ISSUE THREAD

**Issue by ejames604** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#76]
Whilst browsing the code I saw the following in adc.c...

```
  // read and average a few values of ADC battery current
  ui16_adc_battery_current_offset = 0;
  for (ui8_i = 0; ui8_i <= 16; ui8_i++)
  {
    ui16_counter = TIM3_GetCounter () + 10; // delay ~10ms
    while (TIM3_GetCounter () < ui16_counter) ; // delay ~10ms
    adc_trigger ();
    while (!ADC1_GetFlagStatus (ADC1_FLAG_EOC)) ; // wait for end of conversion
    ui16_adc_battery_current_offset += UI8_ADC_BATTERY_CURRENT;
  }
  ui16_adc_battery_current_offset >>= 4;
  ui8_adc_battery_current_offset = ui16_adc_battery_current_offset >> 2;
ui8_adc_motor_phase_current_offset = ui8_adc_battery_current_offset;
```
Shouldn't the condition in the for-loop be <16 not <= 16 ?
As it stands you are going through the loop 17 times (since you start from 0) and then dividing by 16 to average. 

The same idiom is also used for the torque sensor. 

You can also save a few instructions by doing ++ui8_i instead of ui8_i++ as the last bit of the for loop.

**Comment by emyr666** [comment]
same idiom used for the torque sensor
