### ISSUE TITLE
KT-LCD3U on ebike EXS E-Response with motor EXF brushless max speed

### ISSUE THREAD

**Issue by dummys** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#83]
Hello,

I'm looking to change the max speed of my bike and I followed tutorial, but when I want to change it, nothing move, it stays to 25km/h. Is there a way to modify it ? I can dump the firmware using stlink but I don't know where to change this "locking" mecanism. I'm afraid to flash your firmware because I really don't know what the motor is and the vendor don't know too. There is very little details about this bike.

**Comment by leon927** [comment]
Hello,

The open source firmware is only compatible with the motor and controller in the TSDZ2 kit. This is an aftermarket kit that you install on bikes.

The display is maybe the same on your bike but not the drive system. 

You can not use the open source KT-LCD3 firmware without a TSDZ2 motor and controller. Google: TSDZ2.

If you have a bike with the TSDZ2 motor and controller installed you can ask for help in the official forum on this link and we will be happy to help:

https://endless-sphere.com/forums/viewtopic.php?f=30&t=93818&start=9999
