### ISSUE TITLE
Assist multiplier too strong

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#84]
Seems that the 0.19 beta firmware introduced a sort of assist multiplier that resulted in a "way too strong" response.

Forse info, my 5 assistance levels are: 0.1/0.2/0.5/0.8/1.2

**Comment by leon927** [comment]
@casainho - Should have been improved in the latest beta?

**Comment by casainho** [comment]
We need to validate the human power. I will close.

**Comment by leon927** [comment]
Yes, we will do that soon! Great!
