### ISSUE TITLE
Offroad Mode settings have strange logic

### ISSUE THREAD

**Issue by webtech-greg** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#90]
Explanation:
With Ver. 0.19 I can set max speed and max power with config options 0:1 and 8:1, then if I wish to enable Offroad Mode (OM) I override these settings with options 9:2 and 9:4.
To limit OM top speed I have to re-edit option 0:1. Option 8:1 (max power) appears to be ignored if OM is active, there appears to be no way to limit max power in OM other than using option 1:0 to limit the current, but this isn't a constant max limit of power as it fluctuates with voltage and is applied to both Offroad and normal modes.
Would it not be better to have OM options 9:2 and 9:4 set max speed and max power for OM and normal mode restrictions remain as is using options 0:1 and 8:1 ?

**Comment by leon927** [comment]
@casainho - We can now close this as it is solved in the latest beta and thereby the stable 0.19.0.
