### ISSUE TITLE
Error code 1 happens frequently when it should not

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#93]

**Comment by arnoutzw** [comment]
Hi Casainho, I noticed this error popping up also a lot, do you have already a clue what might be causing it?

Thanks!

Btw, I really like the opensource firmware and  hope to contribute to the project in the future!

Best regards, 

Arnout

**Comment by Dirkkro** [comment]
This is  is the code when you have force on the pedal, and the pedals are not moving.  after  some seconsd the  power is swiched off. 
As a workaround you can  try to diable  "power without pedal rotation"  You may be supprised  how fast the engine is pushung in a  very small fraction of rotation !

**Comment by leon927** [comment]
@casainho - We can now close this as it is solved in the latest beta and thereby the stable 0.19.0.
